import { drizzleZeroConfig } from 'drizzle-zero';
import * as schema from './src/lib/server/db/schema';

export default drizzleZeroConfig(schema, {
  tables: {
    profiles: {
      id: true,
      name: true,
      avatarKey: true,
      createdAt: true,
      updatedAt: true,
    },
    mediaRoots: {
      id: true,
      path: true,
      displayName: true,
      mediaType: true,
      displayOrder: true,
      lastScannedAt: true,
    },
    mediaEntries: {
      id: true,
      mediaRootId: true,
      parentId: true,
      name: true,
      kind: true,
      sortOrder: true,
      extension: true,
      isVideo: true,
      isAudio: true,
      durationMs: true,
      container: true,
      audioCodecSummary: true,
      audioBitrate: true,
      audioSampleRate: true,
      audioBitDepth: true,
      audioChannels: true,
      audioChannelLayout: true,
      title: true,
      artist: true,
      album: true,
      albumArtist: true,
      trackNumber: true,
      artworkMediaEntryId: true,
      deletedAt: true,
    },
    playlists: {
      id: true,
      profileId: true,
      name: true,
      createdAt: true,
      updatedAt: true,
    },
    playlistItems: {
      id: true,
      playlistId: true,
      mediaEntryId: true,
      position: true,
      createdAt: true,
    },
    mediaTracks: false,
    externalSubtitles: false,
    playbackProgress: {
      profileId: true,
      mediaEntryId: true,
      positionMs: true,
      durationMs: true,
      watched: true,
      lastPlayedAt: true,
      updatedAt: true,
    },
    trackPlays: {
      id: true,
      profileId: true,
      mediaEntryId: true,
      playedAt: true,
    },
    scanRuns: false,
    scanErrors: false,
    scanJobs: false,
  },
});
