// @generated drizzle-zero signature:sha256:bc56ad3b56569aa305c1d8dc8af5ed553e7ce0b59e267e40d8bbc64333a2ce88
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from '@rocicorp/zero';
import { createBuilder } from '@rocicorp/zero';

const mediaChaptersTable = {
  name: 'mediaChapters',
  columns: {
    mediaEntryId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'media_entry_id',
    },
    position: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    startMs: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'start_ms',
    },
    endMs: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'end_ms',
    },
    title: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['mediaEntryId', 'position'],
  serverName: 'media_chapters',
} as const;
const mediaEntriesTable = {
  name: 'mediaEntries',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    mediaRootId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'media_root_id',
    },
    parentId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'parent_id',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    kind: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    sortOrder: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'sort_order',
    },
    extension: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    isVideo: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'is_video',
    },
    isAudio: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'is_audio',
    },
    durationMs: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'duration_ms',
    },
    container: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    title: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    artist: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    album: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    albumArtist: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'album_artist',
    },
    trackNumber: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'track_number',
    },
    artworkMediaEntryId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'artwork_media_entry_id',
    },
    audioCodecSummary: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'audio_codec_summary',
    },
    audioBitrate: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'audio_bitrate',
    },
    audioSampleRate: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'audio_sample_rate',
    },
    audioBitDepth: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'audio_bit_depth',
    },
    audioChannels: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'audio_channels',
    },
    audioChannelLayout: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'audio_channel_layout',
    },
    deletedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'deleted_at',
    },
  },
  primaryKey: ['id'],
  serverName: 'media_entries',
} as const;
const mediaRootsTable = {
  name: 'mediaRoots',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    path: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    displayName: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'display_name',
    },
    mediaType: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'media_type',
    },
    displayOrder: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'display_order',
    },
    lastScannedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'last_scanned_at',
    },
    source: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
  serverName: 'media_roots',
} as const;
const playbackProgressTable = {
  name: 'playbackProgress',
  columns: {
    profileId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'profile_id',
    },
    mediaEntryId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'media_entry_id',
    },
    positionMs: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'position_ms',
    },
    durationMs: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'duration_ms',
    },
    watched: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
    },
    lastPlayedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'last_played_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['profileId', 'mediaEntryId'],
  serverName: 'playback_progress',
} as const;
const playlistItemsTable = {
  name: 'playlistItems',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    playlistId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'playlist_id',
    },
    mediaEntryId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'media_entry_id',
    },
    position: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
  },
  primaryKey: ['id'],
  serverName: 'playlist_items',
} as const;
const playlistsTable = {
  name: 'playlists',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    profileId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'profile_id',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['id'],
} as const;
const profilesTable = {
  name: 'profiles',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    avatarKey: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'avatar_key',
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['id'],
} as const;
const trackPlaysTable = {
  name: 'trackPlays',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    profileId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'profile_id',
    },
    mediaEntryId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'media_entry_id',
    },
    playedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'played_at',
    },
  },
  primaryKey: ['id'],
  serverName: 'track_plays',
} as const;
const youtubeDownloadsTable = {
  name: 'youtubeDownloads',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    videoId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'video_id',
    },
    url: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    state: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    title: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    channel: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    durationMs: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'duration_ms',
    },
    downloadedBytes: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'downloaded_bytes',
    },
    totalBytes: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'total_bytes',
    },
    mediaEntryId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'media_entry_id',
    },
    errorMessage: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'error_message',
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
    completedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'completed_at',
    },
  },
  primaryKey: ['id'],
  serverName: 'youtube_downloads',
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    mediaChapters: mediaChaptersTable,
    mediaEntries: mediaEntriesTable,
    mediaRoots: mediaRootsTable,
    playbackProgress: playbackProgressTable,
    playlistItems: playlistItemsTable,
    playlists: playlistsTable,
    profiles: profilesTable,
    trackPlays: trackPlaysTable,
    youtubeDownloads: youtubeDownloadsTable,
  },
  relationships: {},
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "mediaChapters" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type MediaChapter = Row<(typeof schema)['tables']['mediaChapters']>;
/**
 * Represents a row from the "mediaEntries" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type MediaEntry = Row<(typeof schema)['tables']['mediaEntries']>;
/**
 * Represents a row from the "mediaRoots" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type MediaRoot = Row<(typeof schema)['tables']['mediaRoots']>;
/**
 * Represents a row from the "playbackProgress" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PlaybackProgress = Row<(typeof schema)['tables']['playbackProgress']>;
/**
 * Represents a row from the "playlistItems" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PlaylistItem = Row<(typeof schema)['tables']['playlistItems']>;
/**
 * Represents a row from the "playlists" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Playlist = Row<(typeof schema)['tables']['playlists']>;
/**
 * Represents a row from the "profiles" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Profile = Row<(typeof schema)['tables']['profiles']>;
/**
 * Represents a row from the "trackPlays" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TrackPlay = Row<(typeof schema)['tables']['trackPlays']>;
/**
 * Represents a row from the "youtubeDownloads" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type YoutubeDownload = Row<(typeof schema)['tables']['youtubeDownloads']>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
  interface DefaultTypes {
    schema: Schema;
  }
}
